# Generated by Django 2.2.14 on 2020-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gordinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=256)),
                ('nome', models.CharField(max_length=256)),
            ],
        ),
    ]
